services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: node:22
    command: "./script.sh"
    tty: true
    # stdin_open: true
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
